"""added private chat message model, updated private chat model

Revision ID: ca198904746c
Revises: c56af23c1124
Create Date: 2026-08-25 09:42:31.165927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca198904746c'
down_revision: Union[str, Sequence[str], None] = 'c56af23c1124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_chat_messages',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('receiver_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['private_chats.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.UniqueConstraint('id', 'chat_id', name='unique_private_chat_message')
    )
    op.add_column('private_chats', sa.Column('last_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'private_chats', 'private_chat_messages', ['last_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'private_chats', type_='foreignkey')
    op.drop_column('private_chats', 'last_message_id')
    op.drop_table('private_chat_messages')
    # ### end Alembic commands ###
