"""added statuses and hashed passwords columns in user model

Revision ID: b0f05e0357bc
Revises: b38055f88d12
Create Date: 2026-06-14 14:00:44.544342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b0f05e0357bc'
down_revision: Union[str, Sequence[str], None] = 'b38055f88d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    
    users_status_enum = postgresql.ENUM('USER', 'ADMIN', 'DELETED', name='userstatus', create_type=False)
    users_status_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('users', sa.Column('status', users_status_enum, nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'status')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
