"""added refresh id coulumn in users sessions model

Revision ID: ee889258ab1a
Revises: 142b05544f26
Create Date: 2026-06-18 12:14:33.099241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee889258ab1a'
down_revision: Union[str, Sequence[str], None] = '142b05544f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_sessions', sa.Column('refresh_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'users_sessions', ['refresh_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_sessions', type_='unique')
    op.drop_column('users_sessions', 'refresh_id')
    # ### end Alembic commands ###
