"""added is_main column in users sessions model

Revision ID: 9cb631e39835
Revises: ee889258ab1a
Create Date: 2026-06-18 13:56:34.685571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb631e39835'
down_revision: Union[str, Sequence[str], None] = 'ee889258ab1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_sessions', sa.Column('is_main', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_sessions', 'is_main')
    # ### end Alembic commands ###
