"""added sender session id ot private chat message model

Revision ID: 92c82fd63cbf
Revises: 1e590d9a31c1
Create Date: 2026-08-28 19:57:06.557043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c82fd63cbf'
down_revision: Union[str, Sequence[str], None] = '1e590d9a31c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('private_chat_messages', 'sender_session_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('private_chat_messages', 'sender_session_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
