"""set chat_id column primary_key=True in private chat message model

Revision ID: fb50f9a2ea8c
Revises: ca198904746c
Create Date: 2026-08-26 08:32:01.958192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb50f9a2ea8c'
down_revision: Union[str, Sequence[str], None] = 'ca198904746c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE private_chat_messages DROP CONSTRAINT private_chat_messages_pkey CASCADE')
    # op.drop_constraint("private_chat_messages_pkey", "private_chat_messages", "primary")
    op.create_primary_key("private_chat_messages_pkey", 'private_chat_messages', ["id", 'chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
