"""created user session model

Revision ID: a08245faf05f
Revises: 6db87a010a00
Create Date: 2026-06-16 21:02:38.497275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08245faf05f'
down_revision: Union[str, Sequence[str], None] = '6db87a010a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_sessions',
    # sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7(monotonic=True)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('last_online', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_sessions')
    # ### end Alembic commands ###
