"""set sessions_count nullable in user model

Revision ID: 3613133ed754
Revises: 8b86da58c28e
Create Date: 2026-07-08 12:29:13.169734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3613133ed754'
down_revision: Union[str, Sequence[str], None] = '8b86da58c28e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sessions_count',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sessions_count',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###
