"""added expires at columt to user session model

Revision ID: edd6e072f13f
Revises: a08245faf05f
Create Date: 2026-06-17 13:21:22.401768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd6e072f13f'
down_revision: Union[str, Sequence[str], None] = 'a08245faf05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_sessions', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_sessions', 'expires_at')
    # ### end Alembic commands ###
