"""added public keys as bytes column to user session model

Revision ID: 4064ba86530f
Revises: 7acd85d10998
Create Date: 2026-07-20 11:24:18.391546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4064ba86530f'
down_revision: Union[str, Sequence[str], None] = '7acd85d10998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_sessions', sa.Column('public_key', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_sessions', 'public_key')
    # ### end Alembic commands ###
