"""added sessions_count column to user model

Revision ID: 8b86da58c28e
Revises: 219c1b6e9deb
Create Date: 2026-07-08 12:23:39.481249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b86da58c28e'
down_revision: Union[str, Sequence[str], None] = '219c1b6e9deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sessions_count', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sessions_count')
    # ### end Alembic commands ###
