"""removed encrypted refresh token column from user sessions model

Revision ID: 142b05544f26
Revises: edd6e072f13f
Create Date: 2026-06-18 10:53:09.331163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142b05544f26'
down_revision: Union[str, Sequence[str], None] = 'edd6e072f13f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_sessions', 'encrypted_refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_sessions', sa.Column('encrypted_refresh_token', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
