"""added sender session id ot private chat message model

Revision ID: 1e590d9a31c1
Revises: dee51e27b115
Create Date: 2026-08-28 19:54:43.937386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e590d9a31c1'
down_revision: Union[str, Sequence[str], None] = 'dee51e27b115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('private_chat_messages', sa.Column('sender_session_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('private_chat_messages', 'sender_session_id')
    # ### end Alembic commands ###
