"""added is_read column to private chat model

Revision ID: dee51e27b115
Revises: af90ed832d0b
Create Date: 2026-08-28 18:11:14.395000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee51e27b115'
down_revision: Union[str, Sequence[str], None] = 'af90ed832d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('private_chat_messages', sa.Column('is_read', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('private_chat_messages', 'is_read')
    # ### end Alembic commands ###
