"""set last_message_id column nullable=False in private chat model

Revision ID: af90ed832d0b
Revises: fb50f9a2ea8c
Create Date: 2026-08-26 10:13:23.758103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af90ed832d0b'
down_revision: Union[str, Sequence[str], None] = 'fb50f9a2ea8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('private_chats', 'last_message_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    # op.create_foreign_key(None, 'private_chats', 'private_chat_messages', ['last_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'private_chats', type_='foreignkey')
    op.alter_column('private_chats', 'last_message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
